2LabsToGo-Eco-Software/app/app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('finecontrol.urls')),
    path('', include('connection.urls')),
    path('', include('sampleapp.urls')),
    path('', include('development.urls')),
    path('', include('detection.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

2LabsToGo-Eco-Software/app/sampleapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
import finecontrol.models as core_models
# To have a better understandig on the Fields of the Database read pySerial
# documentation. Mostly just the "class serial.Serial" parameters

class SampleApplication_Db(core_models.Application_Db):
    class Meta(core_models.Application_Db.Meta):
        pass


class PlateProperties_Db(core_models.PlateProperties_Db):
    sample_application = models.ForeignKey(SampleApplication_Db,
                                    related_name='plate_properties',
                                    null=True,
                                    on_delete=models.CASCADE,
                                    blank=True)

class ZeroPosition_Db(core_models.ZeroPosition_Db):
    sample_application = models.ForeignKey(SampleApplication_Db,
                                    related_name='zero_properties',
                                    null=True,
                                    on_delete=models.CASCADE,
                                    blank=True)

class BandsComponents_Db(models.Model):
    sample_application = models.ForeignKey(SampleApplication_Db,
                                                             related_name='band_components',
                                                             null=True,
                                                             on_delete=models.CASCADE,
                                                             blank=True)
    band_number = models.DecimalField(decimal_places=0, max_digits=3, null=True, blank=True)
    product_name = models.CharField(null=True, max_length=120, blank=True)
    volume = models.DecimalField(decimal_places=2, max_digits=6, null=True, blank=True)
    type = models.CharField(null=True, max_length=120, blank=True)
    sample = models.DecimalField(decimal_places=0, max_digits=1, null=True, blank=True)
    density = models.DecimalField(decimal_places=2, max_digits=6, null=True, blank=True)
    viscosity = models.DecimalField(decimal_places=2, max_digits=6, null=True, blank=True)
    

class BandSettings_Db(models.Model):
    sample_application = models.ForeignKey(SampleApplication_Db,
                                                                 related_name='band_settings',
                                                                 null=True,
                                                                 on_delete=models.CASCADE,
                                                                 blank=True)
    main_property = models.DecimalField(null=True,decimal_places=0, max_digits=6)
    value = models.DecimalField(null=True, decimal_places=0, max_digits=3)
    height = models.DecimalField(null=True, decimal_places=2, max_digits=5)
    gap = models.DecimalField(null=True, decimal_places=2, max_digits=5)
    waitTime = models.DecimalField(null=True, decimal_places=2, max_digits=5)

class MovementSettings_Db(models.Model):
    sample_application = models.ForeignKey(SampleApplication_Db,
                                                                 related_name='movement_settings',
                                                                 null=True,
                                                                 on_delete=models.CASCADE,
                                                                 blank=True)
    motor_speed = models.DecimalField(null=True, decimal_places=0, max_digits=5)
    delta_x = models.DecimalField(null=True, decimal_places=2, max_digits=5)
    delta_y = models.DecimalField(null=True, decimal_places=2, max_digits=5)

class PressureSettings_Db(models.Model):
    sample_application = models.ForeignKey(SampleApplication_Db,
                                                                 related_name='pressure_settings',
                                                                 null=True,
                                                                 on_delete=models.CASCADE,
                                                                 blank=True)
    pressure = models.DecimalField(null=True, decimal_places=0, max_digits=3)
    frequency = models.DecimalField(null=True, decimal_places=0, max_digits=4)
    temperature = models.DecimalField(null=True, decimal_places=0, max_digits=3, blank=True)
    nozzlediameter = models.CharField(max_length=120, default='0.05')
    rinsingPeriod = models.DecimalField(null=True, decimal_places=0, max_digits=6)
    rinsingSolvent = models.CharField(null=True, max_length=120, blank=True)

2LabsToGo-Eco-Software/app/templates/modules/sampleappsp/dinamicpropertiesformsp.html
{% load static %}
<form class="volume-calculation-parameter" id='movementform'>
    <div class="form-group row">
        <div class="input-group input-group-sm">
            <label for="id_motor_speed" class="col-xl-3 col-lg-5 col-form-label col-form-label-sm text-truncate">X Motor Speed</label>
            <input type="number" name="motor_speed" value="1000" class="form-control" step="1" required="" id="id_motor_speed">
            <div class="input-group-append">
                <span class="input-group-text">mm/s</span>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="input-group input-group-sm">
            <label for="id_pressure" class="col-xl-3 col-lg-5 col-form-label col-form-label-sm text-truncate" >Pressure</label>
            <input type="number" name="pressure" value="5" min="5" class="form-control change-volume-parameter" step="1" required="" id="id_pressure">
            <div class="input-group-append">
                <span class="input-group-text">psi</span>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="input-group input-group-sm">
            <label for="id_frequency" class="col-xl-3 col-lg-5 col-form-label col-form-label-sm text-truncate">Frequency</label>
            <input type="number" name="frequency" value="1200" class="form-control change-volume-parameter" step="1" required="" id="id_frequency">
            <div class="input-group-append">
                <span class="input-group-text">Hz</span>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="input-group input-group-sm">
            <label for="id_delta_y" class="col-xl-3 col-lg-5 col-form-label col-form-label-sm text-truncate">Delta Y</label>
            <input type="number" name="delta_y" value="0.75" class="form-control change-volume-parameter" step="0.01" required="" id="id_delta_y">
            <div class="input-group-append">
                <span class="input-group-text">mm</span>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="input-group input-group-sm">
            <label for="id_delta_x" class="col-xl-3 col-lg-5 col-form-label col-form-label-sm text-truncate">Delta X</label>
            <input type="number" name="delta_x" value="0.75" class="form-control change-volume-parameter" step="0.01" required="" id="id_delta_x">
            <div class="input-group-append">
                <span class="input-group-text">mm</span>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="input-group input-group-sm">
            <label for="id_temperature" class="col-xl-3 col-lg-5 col-form-label col-form-label-sm text-truncate">Temperature</label>
            <input type="number" name="temperature" value="0" class="form-control" step="1" id="id_temperature">
            <div class="input-group-append">
                <span class="input-group-text">°C</span>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="input-group input-group-sm">
            <label for="id_nozzlediameter" class="col-xl-3 col-lg-5 col-form-label col-form-label-sm text-truncate">Nozzle</label>
            <select name="nozzlediameter" class="form-control change-volume-parameter" maxlength="120" id="id_nozzlediameter">
                <option value="0.13" selected="">0.13</option>
                <option value="0.10">0.10</option>
                <option value="0.08">0.08</option>
                <option value="0.05">0.05</option>
            </select>
            <div class="input-group-append">
                <span class="input-group-text">mm</span>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="input-group input-group-sm">
            <label for="id_rinsingperiod" class="col-xl-3 col-lg-5 col-form-label col-form-label-sm text-truncate">Rinsing Period</label>
            <input type="number" name="rinsingPeriod" value="99999" class="form-control" step="1" id="id_rinsingperiod">
            <div class="input-group-append">
                <span class="input-group-text">#drops</span>
            </div>
        </div>
    </div>
</form>

2LabsToGo-Eco-Software/app/templates/modules/sampleappsp/offsetssp.html
<p><b>Offsets<hr></b><p>
<div class="alert alert-warning collapse" id='id_offsets_error' role="alert">
    The sum of the offsets should be smaller than the plate size
</div>
<div class="form-group row">
    <div class="input-group input-group-sm col p-0">
        <label for="id_offset_left" class="col-xl-3 col-lg-3 col-form-label col-form-label-sm text-truncate px-0 mx-1">Left</label>
        <input type="number" name="offset_left" value="1" class="form-control change-graph-size-parameter development-flowrate-insidence" step="0.01" required="" id="id_offset_left">
        <div class="input-group-append">
            <span class="input-group-text">mm</span>
        </div>
    </div>
</div>
<div class="form-group row">
    <div class="input-group input-group-sm col p-0">
        <label for="id_offset_right" class="col-xl-3 col-lg-3 col-form-label col-form-label-sm text-truncate px-0 mx-1">Right</label>
        <input type="number" name="offset_right" value="1" class="form-control change-graph-size-parameter development-flowrate-insidence" step="0.01" required="" id="id_offset_right">
        <div class="input-group-append">
            <span class="input-group-text">mm</span>
        </div>
    </div>
</div>
<div class="form-group row">
    <div class="input-group input-group-sm col p-0">
        <label for="id_offset_bottom" class="col-xl-3 col-lg-3 col-form-label col-form-label-sm text-truncate px-0 mx-1">Bottom</label>
        <input type="number" name="offset_bottom" value="1" class="form-control change-graph-size-parameter" step="0.01" required="" id="id_offset_bottom">
        <div class="input-group-append">
            <span class="input-group-text">mm</span>
        </div>
    </div>
</div>

2LabsToGo-Eco-Software/app/templates/modules/sampleappsp/platepropertiesformsp.html
{% load static %}
<form class="volume-calculation-parameter" id="plateform">
    {% include 'modules/sampleappsp/platesizessp.html' %}
    {% include 'modules/sampleappsp/offsetssp.html' %}
    <div class="form-group row pt-4">
        <div class="input-group input-group-sm">
            <label for="id_main_property" class="col-xl-3 col-form-label col-form-label-sm text-truncate"><h6><b>Band Calculation</b></h1></label>
            <select name="main_property" class="form-control" id="id_main_property">
                <option value="1">Number of Bands</option>
                <option value="2">Band Length</option>
            </select>
        </div>
    </div>
    <hr/>
    <div class="alert alert-warning alert-dismissible collapse" id='id_gap_error' role="alert">
        Reduce gap size for given number of bands
    </div>
    <div class="alert alert-warning alert-dismissible collapse" id='id_space_error' role="alert">
        There is not enough space for these parameters
    </div>
    <div class="form-group mt-3 mb-1 row" id='id_valuesform'>
        <div class="input-group input-group-sm">
            <label for="id_value" class="col-xl-2 col-form-label col-form-label-sm text-truncate" id="valueLabel">Number</label>
            <input type="number" name="value" value="2" class="form-control change-graph-size-parameter change-bands-table" step="1" required="" id="id_value">
            <div class="input-group-append">
                <span id='id_valuesunit' class="input-group-text">#</span>
            </div>
        </div>
    </div>
    <div class="form-group mb-1 row">
        <div class="input-group input-group-sm">
            <label for="id_height" class="col-xl-2 col-form-label col-form-label-sm text-truncate">Height</label>
            <input type="number" name="height" value="0" class="form-control change-graph-size-parameter" step="0.01" required="" id="id_height">
            <div class="input-group-append">
                <span class="input-group-text">mm</span>
            </div>
        </div>
        <div class="input-group input-group-sm">
            <label for="id_gap" class="col-xl-2 col-form-label col-form-label-sm text-truncate">Gap</label>
            <input type="number" name="gap" value="4" class="form-control change-graph-size-parameter" step="0.01" required="" id="id_gap">
            <div class="input-group-append">
                <span class="input-group-text">mm</span>
            </div>
        </div>
    
        <div class="input-group input-group-sm">
            <label for="id_waitTime" class="col-xl-2 col-form-label col-form-label-sm text-truncate">Pause</label>
            <input type="number" name="waitTime" value="0" class="form-control change-graph-size-parameter" step="1" required="" id="id_waitTime">
            <div class="input-group-append">
                <span class="input-group-text">s</span>
            </div>
        </div>
    </div>
</form>

2LabsToGo-Eco-Software/app/templates/modules/sampleappsp/platesizessp.html
<p><b>Plate Size</b><hr/><p>
<div class="form-group mt-3 mb-1 row">
    <div class="input-group input-group-sm">
        <div class="input-group-prepend">
            <span class="input-group-text">X</span>
        </div>
        <input type="number" name="size_x" value="100" class="form-control development-flowrate-insidence change-graph-size-parameter change-bands-table" step="1" required="" id="id_size_x">
        <div class="input-group-append">
            <span class="input-group-text">mm</span>
        </div>
    </div>
</div>
<div class="form-group row pb-4">
    <div class="input-group input-group-sm">
        <div class="input-group-prepend">
            <span class="input-group-text">Y</span>
        </div>
        <input type="number" name="size_y" value="100" class="form-control change-graph-size-parameter change-bands-table" step="1" required="" id="id_size_y">
        <div class="input-group-append">
            <span class="input-group-text">mm</span>
        </div>
    </div>
</div>