2LabsToGo-Eco-Software/app/app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('finecontrol.urls')),
    path('', include('connection.urls')),
    path('', include('sampleapp.urls')),
    path('', include('development.urls')),
    path('', include('detection.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

2LabsToGo-Eco-Software/app/sampleapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
import finecontrol.models as core_models
# To have a better understandig on the Fields of the Database read pySerial
# documentation. Mostly just the "class serial.Serial" parameters

class SampleApplication_Db(core_models.Application_Db):
    class Meta(core_models.Application_Db.Meta):
        pass


class PlateProperties_Db(core_models.PlateProperties_Db):
    sample_application = models.ForeignKey(SampleApplication_Db,
                                    related_name='plate_properties',
                                    null=True,
                                    on_delete=models.CASCADE,
                                    blank=True)

class ZeroPosition_Db(core_models.ZeroPosition_Db):
    sample_application = models.ForeignKey(SampleApplication_Db,
                                    related_name='zero_properties',
                                    null=True,
                                    on_delete=models.CASCADE,
                                    blank=True)

class BandsComponents_Db(models.Model):
    sample_application = models.ForeignKey(SampleApplication_Db,
                                                             related_name='band_components',
                                                             null=True,
                                                             on_delete=models.CASCADE,
                                                             blank=True)
    band_number = models.DecimalField(decimal_places=0, max_digits=3, null=True, blank=True)
    product_name = models.CharField(null=True, max_length=120, blank=True)
    volume = models.DecimalField(decimal_places=2, max_digits=6, null=True, blank=True)
    type = models.CharField(null=True, max_length=120, blank=True)
    sample = models.DecimalField(decimal_places=0, max_digits=1, null=True, blank=True)
    density = models.DecimalField(decimal_places=2, max_digits=6, null=True, blank=True)
    viscosity = models.DecimalField(decimal_places=2, max_digits=6, null=True, blank=True)
    

class BandSettings_Db(models.Model):
    sample_application = models.ForeignKey(SampleApplication_Db,
                                                                 related_name='band_settings',
                                                                 null=True,
                                                                 on_delete=models.CASCADE,
                                                                 blank=True)
    main_property = models.DecimalField(null=True,decimal_places=0, max_digits=6)
    value = models.DecimalField(null=True, decimal_places=0, max_digits=3)
    height = models.DecimalField(null=True, decimal_places=2, max_digits=5)
    gap = models.DecimalField(null=True, decimal_places=2, max_digits=5)
    waitTime = models.DecimalField(null=True, decimal_places=2, max_digits=5)

class MovementSettings_Db(models.Model):
    sample_application = models.ForeignKey(SampleApplication_Db,
                                                                 related_name='movement_settings',
                                                                 null=True,
                                                                 on_delete=models.CASCADE,
                                                                 blank=True)
    motor_speed = models.DecimalField(null=True, decimal_places=0, max_digits=5)
    delta_x = models.DecimalField(null=True, decimal_places=2, max_digits=5)
    delta_y = models.DecimalField(null=True, decimal_places=2, max_digits=5)

class PressureSettings_Db(models.Model):
    sample_application = models.ForeignKey(SampleApplication_Db,
                                                                 related_name='pressure_settings',
                                                                 null=True,
                                                                 on_delete=models.CASCADE,
                                                                 blank=True)
    pressure = models.DecimalField(null=True, decimal_places=0, max_digits=3)
    frequency = models.DecimalField(null=True, decimal_places=0, max_digits=4)
    temperature = models.DecimalField(null=True, decimal_places=0, max_digits=3, blank=True)
    nozzlediameter = models.CharField(max_length=120, default='0.05')
    rinsingPeriod = models.DecimalField(null=True, decimal_places=0, max_digits=6)
    rinsingSolvent = models.CharField(null=True, max_length=120, blank=True)

2LabsToGo-Eco-Software/app/templates/modules/staticpurge/staticpurge.html
{% load static %}
<div class="card shadow mb-4" id='staticpurgecard'>
  <div class="card-header py-3">
    <div class="d-flex flex-row justify-content-between align-items-center">
      <h6 class="m-0 font-weight-bold text-primary w-100 align-self-center">Static Purge</h6>
      <button id='syringe-settings'class="btn btn-link"  data-toggle="modal" data-target="#syringeModal"><i class="fas fa-syringe"></i></button>
    </div>
  </div>
  <div class="card-body">
    <form id='static-form' method="post"> {% csrf_token %}
      <div class="input-group">
        <label for="colFormLabelSm" class="col-xl-2 col-form-label col-form-label-sm text-truncate">Volume</label>
        <input type="number" name="volume" class='form-control px-1' value="500" id='id_volume'/>
        <div class="input-group-append">
            <span class="input-group-text">uL</span>
        </div>
      </div>
      </br>
      <div class="input-group">
        <label for="colFormLabelSm" class="col-xl-2 col-form-label col-form-label-sm text-truncate">Speed</label>
        <input type="number" name="speed" value="1" class="form-control" step="0.1" required="" id="id_speed">
        <div class="input-group-append">
            <span class="input-group-text">mm/s</span>
        </div>
      </div>
      </br>
      <div class="float-right">
        <button class="btn btn-secondary btn-icon-split btn-sm" id='pump_manual' type="submit">
          <span class="icon text-white-50">
            <i class="fas fa-gas-pump"></i>
          </span>
          <span class="text">Start!</span>
        </button>
      </div>
      <br>
    </form>
  </div>
  <div class="card-footer text-muted">
    <div class="d-flex justify-content-end">
      <button class="btn btn-secondary btn-icon-split btn-sm" id='next_bttn_stat'>
        <span class="icon text-white-50">
          <i class="fas fa-forward"></i>
        </span>
        <span class="text">Next Step!</span>
      </button>
      <button class="btn btn-secondary btn-icon-split btn-sm" id='restart_bttn_dina'  style="display: none">
        <span class="icon text-white-50">
          <i class="fas fa-forward"></i>
        </span>
        <span class="text">Restart</span>
      </button>
    </div>
  </div>
</div>

<script src="{% static 'modules/staticpurge/staticpurge.js' %}"></script>
{% include 'modules/syringeload/syringeload.html' %}